#define CHECK_MAX_PLAYERS		//additional option 
#define CHECK_RCON_PASSWORD		//additional option 
#define CHECK_SERVER_LANGUAGE	//additional option 

#define FILE_SERVERIP			"80.72.36.205" 
#define FILE_SERVERPORT			(4040) 
#define FILE_LICENSEID			(20170201)		//<--- YYYYMMDD 01.02.2016 (DD.MM.YYYY) 
#define FILE_MAX_PLAYERS		(MAX_PLAYERS)	//max players in server.cfg 
#define FILE_RCONPASS			"limmi"			//rcon password 
#define FILE_LANGUAGE			"Polish"		//server language 